language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t matepocz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matepocz/docker-react npm run test